"CREATE TABLE " + contactInfo + "("
            + noteName + " VARCHAR(32),"
            + name + " VARCHAR(32),"
            + homeAddress + " VARCHAR(64),"
            + workAddress + " VARCHAR(64),"
            + career + " VARCHAR(32),"
            + contactId + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + phoneNumber + " VARCHAR(32),"
            + avaterUrl + " VARCHAR(100),"
            + ")";